'use strict';
const data=window.PORTFOLIO;
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=value=>/^(https?:|mailto:)/i.test(value)||(!/^[a-z]+:/i.test(value)&&!value.startsWith('//'))?value:'#';
$('name').textContent=data.name;$('intro').textContent=data.intro;$('about-text').textContent=data.about;$('count').textContent=data.projects.length;
$('copyright').textContent=`© ${new Date().getFullYear()} ${data.name}`;
document.querySelectorAll('.email-link').forEach(a=>a.href='mailto:'+data.email);$('email-text').textContent=data.email;['github','linkedin'].forEach(k=>$(k).href=safeUrl(data[k]));
$('resume').href=data.resume?safeUrl(data.resume):'mailto:'+data.email+'?subject=Resume%20request';if(data.resume){$('resume').textContent='Download resume ↓';$('resume').target='_blank';$('resume').rel='noopener';}
const portrait=document.createElement('img');portrait.alt=data.fullName;portrait.src=safeUrl(data.photo);portrait.onerror=()=>{$('portrait').innerHTML=`<div class="portrait-fallback"><span>HELLO, I’M</span><strong>${esc(data.name)}<span>.</span></strong><p>Flutter Developer<br>Rawalpindi, Pakistan</p><small>Profile photo coming soon</small></div>`};$('portrait').append(portrait);
function shot(p,i){return `<div class="shot" style="--accent:${esc(p.color)}"><img loading="lazy" src="${esc(safeUrl(p.images?.[i]||'assets/images/missing.jpg'))}" alt="${esc(p.screens[i])}"><div class="placeholder" hidden><span class="screen-index">0${i+1} / SCREEN</span><div class="screen-symbol">▧</div><strong>${esc(p.screens[i])}</strong><span>Screenshot coming soon</span><small>PLACEHOLDER</small></div></div>`}
function attachFallbacks(root){root.querySelectorAll('.shot img').forEach(img=>{const fail=()=>{img.hidden=true;img.nextElementSibling.hidden=false};img.addEventListener('error',fail);if(img.complete&&img.naturalWidth===0)fail()})}
const tags=p=>`<div class="tags">${p.stack.map(s=>`<span>${esc(s)}</span>`).join('')}</div>`;
$('projects').innerHTML=data.projects.map((p,i)=>`<article class="project"><button class="project-visual" data-project="${i}" style="--accent:${esc(p.color)}" aria-label="View ${esc(p.name)} case study"><span class="visual-label">${esc(p.tag)}</span><div class="screens">${p.screens.slice(0,2).map((_,j)=>shot(p,j)).join('')}</div><span class="visual-bottom">${esc(p.status)}<span>↗</span></span></button><div class="project-copy"><div class="eyebrow">${esc(p.category)}</div><button class="title-button" data-project="${i}"><h3>${esc(p.name)}</h3><span>↗</span></button><p>${esc(p.description)}</p><ul class="project-highlights">${p.features.slice(0,3).map(f=>`<li>${esc(f)}</li>`).join('')}</ul>${tags(p)}<button class="case-link" data-project="${i}">Explore project ↗</button></div></article>`).join('');attachFallbacks($('projects'));
$('timeline').innerHTML=data.experience.map((x,i)=>`<article class="timeline-row"><span class="career-index">0${i+1}</span><div><span class="eyebrow">${esc(x.date)}</span><h3>${esc(x.name)}</h3><b>${esc(x.role)}</b></div><p>${esc(x.text)}</p></article>`).join('');
$('skills').innerHTML=[['Mobile & Flutter Web','Flutter, Dart, responsive interfaces, reusable widgets, and GetX state management.'],['Firebase & backend workflows','Authentication, Firestore, Storage, Cloud Functions, and shared mobile/admin data.'],['APIs & real-time features','REST APIs, WebSockets, multimedia messaging, file uploads, and notifications.'],['AI & product integrations','Gemini-assisted writing, streamed AI conversations, maps, and Paystack payment workflows.']].map(([t,d],i)=>`<article class="expertise-card"><span>0${i+1}</span><h3>${t}</h3><p>${d}</p></article>`).join('');
const modal=$('case');document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{const p=data.projects[Number(b.dataset.project)];$('case-body').innerHTML=`<div class="eyebrow">${esc(p.category)}</div><h2 id="case-title" class="case-title">${esc(p.name)}</h2><p class="case-description">${esc(p.detail)}</p>${tags(p)}<h4>Implemented workflows</h4><ul>${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><div class="case-gallery">${p.screens.map((_,i)=>shot(p,i)).join('')}</div><p class="case-note">${esc(p.status)}. Screenshots labelled as placeholders are not actual application screens.${p.id==='buy'?' Razorpay and Paystack integration work was undertaken; final checkout remains incomplete.':''}</p>`;attachFallbacks($('case-body'));modal.showModal();document.body.classList.add('modal-open')}));modal.querySelector('button').onclick=()=>modal.close();modal.addEventListener('close',()=>document.body.classList.remove('modal-open'));modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.project,.timeline-row,.expertise-card,.section-heading').forEach(el=>observer.observe(el));
